testNavisaf/testNavisaf/Models/ModelEmpleados.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testNavisaf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpleadosDBEntities : DbContext
    {
        public EmpleadosDBEntities()
            : base("name=EmpleadosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmpleados> tblEmpleados { get; set; }
    }
}

testNavisaf/testNavisaf/Models/ModelEmpleados.Designer.cs
// T4 code generation is enabled for model 'C:\visualstudio\CRUD\testNavisaf\testNavisaf\Models\ModelEmpleados.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

testNavisaf/testNavisaf/Models/ModelEmpleados.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

testNavisaf/testNavisaf/Models/tblEmpleados.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testNavisaf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleados
    {
        public int Id { get; set; }
        public string DocIdentidad { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> NumHijos { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    }
}

testNavisaf/testNavisaf/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testNavisaf.Models;

namespace testNavisaf.Controllers
{
    public class EmpleadoController : Controller
    {

        EmpleadosDBEntities db = new EmpleadosDBEntities();

        // GET: Empleado
        public ActionResult Index()
        {

            return View(db.tblEmpleados.ToList());
        }

        [HttpPost]
        public ActionResult BuscarXDocumento(string Documento)
        {
            var lista = db.tblEmpleados.Where(a => a.DocIdentidad.Contains(Documento));
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult BuscarXNombres(string Nombres)
        {
            var lista = db.tblEmpleados.Where(a => a.Nombres.Contains(Nombres) || a.Apellidos.Contains(Nombres));
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(tblEmpleados empleado)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                if(empleado.Sexo.ToUpper().Equals("M") && (empleado.Edad < 25 || empleado.Edad > 40))
                {
                    ModelState.AddModelError("", string.Format("El empleado {0} debe estar entre los 25 y los 40 años", empleado.Nombres));
                    return View();
                }else if (empleado.Sexo.ToUpper().Equals("F") && (empleado.Edad < 24 || empleado.Edad > 38))
                {
                    ModelState.AddModelError("", string.Format("El empleado {0} debe estar entre los 24 y los 38 años", empleado.Nombres));
                    return View();
                }

                using (db)
                {
                    db.tblEmpleados.Add(empleado);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error al Guardar");
                return View();
            }
        }

        public ActionResult Editar(int id)
        {
            using (db)
            {
                return View(db.tblEmpleados.Find(id));
            }
        }


        [HttpPost]
        public ActionResult Editar(tblEmpleados empleado)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                if (empleado.Sexo.ToUpper().Equals("M") && (empleado.Edad < 25 || empleado.Edad > 40))
                {
                    ModelState.AddModelError("", string.Format("El empleado {0} debe estar entre los 25 y los 40 años", empleado.Nombres));
                    return View();
                }
                else if (empleado.Sexo.ToUpper().Equals("F") && (empleado.Edad < 24 || empleado.Edad > 38))
                {
                    ModelState.AddModelError("", string.Format("El empleado {0} debe estar entre los 24 y los 38 años", empleado.Nombres));
                    return View();
                }

                using (db)
                {
                    tblEmpleados objEpleado = new tblEmpleados();
                    objEpleado = db.tblEmpleados.Find(empleado.Id);

                    objEpleado.DocIdentidad = empleado.DocIdentidad;
                    objEpleado.Nombres = empleado.Nombres;
                    objEpleado.Apellidos = empleado.Apellidos;
                    objEpleado.Edad = empleado.Edad;
                    objEpleado.NumHijos = empleado.NumHijos;
                    objEpleado.Direccion = empleado.Direccion;
                    objEpleado.Ciudad = empleado.Ciudad;
                    objEpleado.Telefono = empleado.Telefono;
                    objEpleado.Sexo = empleado.Sexo;
                    objEpleado.FechaNacimiento = empleado.FechaNacimiento;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error al Guardar");
                return View();
            }
        }

        public ActionResult Eliminar(int id)
        {
            using (db)
            {
                var empleado = db.tblEmpleados.Find(id);
                db.tblEmpleados.Remove(empleado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

testNavisaf/testNavisaf/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace testNavisaf.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

testNavisaf/testNavisaf/Views/Empleado/Crear.cshtml
@model testNavisaf.Models.tblEmpleados

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblEmpleados</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocIdentidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocIdentidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocIdentidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumHijos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumHijos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumHijos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

testNavisaf/testNavisaf/Views/Empleado/Editar.cshtml
@model testNavisaf.Models.tblEmpleados

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblEmpleados</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DocIdentidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocIdentidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocIdentidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumHijos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumHijos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumHijos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

testNavisaf/testNavisaf/Views/Empleado/Index.cshtml
@model IEnumerable<testNavisaf.Models.tblEmpleados>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Empleado", "Crear")
</p>
<table id="empleados" class="table">
    <thead>
        <tr>
            <th width="20%">
                Documento
            </th>
            <th width="40%">
                @Html.DisplayNameFor(model => model.Nombres)
            </th>
            <th width="10%">
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th width="10%">
                @Html.DisplayNameFor(model => model.NumHijos)
            </th>
            <th width="20%"></th>
        </tr>
        <tr>
            <th>
                @Html.TextBox("txtBuscarXDocumento", null, new { @class = "form-control" })
            </th>
            <th>
                @Html.TextBox("txtBuscarXNombres", null, new { @class = "form-control" })
            </th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DocIdentidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombres)
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Edad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumHijos)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                        @Html.ActionLink("Detalles", "Detalle", new { id = item.Id }) |
                        @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
                    </td>
                </tr>
            }
    </tbody>
    </table>

<script>

    let BuscarXDocumento = $('#txtBuscarXDocumento');
    BuscarXDocumento.on('input', function (e) {
        let buscar = e.target.value;
        $.ajax({
            url: '@Url.Action("BuscarXDocumento", "Empleado")',
            type: 'POST',
            data: JSON.stringify({ Documento: buscar }),
            contentType: "application/json; charset=utf-8",
            dataType: 'json',
            success: function (rsl) {
                let tbody = $('#empleados tbody');
                tbody.html('');
                $.each(rsl, function (i, item) {
                    let tr = $('<tr />');
                    tr.append($('<td />').html(item.DocIdentidad));
                    tr.append($('<td />').html(item.Nombres + " " + item.Apellidos));
                    tr.append($('<td />').html(item.Edad));
                    tr.append($('<td />').html(item.NumHijos));
                    let a = $('<td />');
                    a.append($('<a />', { href: '/Empleado/Editar/' + item.Id }).html('Editar | '));
                    a.append($('<a />', { href: '/Empleado/Detalle/' + item.Id }).html('Detalles | '));
                    a.append($('<a />', { href: '/Empleado/Eliminar/' + item.Id }).html('Eliminar |'));
                    a.append($('<a />', { href: '/Empleado/Mapa/' + item.Id }).html('Mapa |'));
                    a.append($('<a />', { href: '/Empleado/Hijos/' + item.Id }).html('Hijos'));
                    tbody.append(tr).append(a);
                });
            }
        });
    });

    let BuscarXNombres = $('#txtBuscarXNombres');
    BuscarXNombres.on('input', function (e) {
        let buscar = e.target.value;
        $.ajax({
            url: '@Url.Action("BuscarXNombres", "Empleado")',
            type: 'POST',
            data: JSON.stringify({ Nombres: buscar }),
            contentType: "application/json; charset=utf-8",
            dataType: 'json',
            success: function (rsl) {
                console.log(rsl)
                let tbody = $('#empleados tbody');
                tbody.html('');
                $.each(rsl, function (i, item) {
                    let tr = $('<tr />');
                    tr.append($('<td />').html(item.DocIdentidad));
                    tr.append($('<td />').html(item.Nombres + " " + item.Apellidos));
                    tr.append($('<td />').html(item.Edad));
                    tr.append($('<td />').html(item.NumHijos));
                    let a = $('<td />');
                    a.append($('<a />', { href: '/Empleado/Editar/' + item.Id }).html('Editar | '));
                    a.append($('<a />', { href: '/Empleado/Detalle/' + item.Id }).html('Detalles | '));
                    a.append($('<a />', { href: '/Empleado/Eliminar/' + item.Id }).html('Eliminar |'));
                    a.append($('<a />', { href: '/Empleado/Mapa/' + item.Id }).html('Mapa |'));
                    a.append($('<a />', { href: '/HijosEmpleado/Hijos/' + item.Id }).html('Hijos'));
                    tr.append(a);
                    tbody.append(tr);
                });
            }
        });
    });

</script>

testNavisaf/testNavisaf/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

testNavisaf/testNavisaf/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

testNavisaf/testNavisaf/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

testNavisaf/testNavisaf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Empleado", "Index", "Empleado")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>